window.BIG_CONTENT = {
  lessons: {
    investing: {
      title: "Investing 101",
      eyebrow: "Education",
      summary: "Learn risk, diversification, time horizon, compounding, and the difference between investing and speculating.",
      audience: "Students and young professionals who want to understand the market before putting money at risk.",
      outcomes: ["Explain what stocks, bonds, funds, and diversification are", "Connect risk to time horizon", "Build a beginner research checklist"],
      sections: [
        {
          title: "Why investing beats saving alone",
          body: "A savings account paying 0.5% APY loses purchasing power every year when inflation runs at 3–4%. Investing puts your money into assets — stocks, bonds, index funds — that historically grow faster than inflation over long periods. The S&P 500 has returned an average of roughly 10% per year before inflation over the past 50 years. That does not mean every year is positive — it means the long-run trend rewards patient, diversified investors. The key insight: $200 per month invested at 8% for 30 years grows to approximately $298,000. The same $200 sitting in a 0.5% savings account becomes about $79,000. Time and return rate are the two most powerful variables in your financial life, and both favor starting early.",
        },
        {
          title: "Risk, time horizon, and diversification",
          body: "Every investment carries risk — the possibility that its value drops. But risk and time horizon are deeply connected. A 22-year-old investing for retirement at 65 has 43 years to recover from market downturns. A 55-year-old needs to retire in 10 years and cannot afford to wait out a decade-long recovery. This is why your time horizon should drive your asset allocation, not headlines or fear. Diversification reduces risk without necessarily reducing returns. When you own 500 companies through an S&P 500 index fund instead of just one stock, a single company's failure does not ruin your portfolio. Stocks, bonds, and cash all move differently in different economic conditions — mixing them is one of the few genuinely free lunches in investing.",
        },
        {
          title: "Accounts matter as much as investments",
          body: "Where you invest is often more important than what you invest in. A Roth IRA lets your money grow completely tax-free — you pay taxes now, but never again on the gains. If you invest $6,000 per year in a Roth IRA starting at 22 and it grows to $800,000 by retirement, you pay zero tax on that $800,000. A traditional 401(k) reduces your taxable income today and taxes you at withdrawal. Most experts suggest: max your 401(k) match first (that is a 50–100% instant return), then fund a Roth IRA, then invest in a standard brokerage account. For beginners, low-cost index ETFs like VTI (total US market), VXUS (international), or BND (bonds) cover almost everything you need at expense ratios below 0.10%.",
        },
        {
          title: "Use AI as a research assistant, not a stock picker",
          body: "AI tools like Claude or ChatGPT are excellent at explaining financial concepts, summarizing SEC filings in plain English, defining unfamiliar terms, and generating research questions you had not thought to ask. They are not reliable for specific buy or sell recommendations, and they cannot predict markets. A useful workflow: paste a company's investor relations summary into AI and ask it to explain the business model, identify the top three risks, and list five questions you should research before forming an opinion. Then verify every fact against the original source. AI accelerates your research — it does not replace your judgment.",
        },
      ],
      checklist: ["Open a Roth IRA or 401(k) if you have not already", "Define the goal and time horizon for this money", "Choose a low-cost index fund as your starting point", "Set a recurring automatic contribution, even if small", "List the risks before committing any money"],
      prompt: "Act as a finance tutor. Explain this investment concept in plain English, list the key risks, define the terms I should understand, and give me five research questions to investigate. Do not recommend whether I should buy or sell. Add an educational disclaimer at the end.",
      apps: [
        { name: "Fidelity", domain: "fidelity.com", url: "https://fidelity.com", note: "Best all-around brokerage for beginners — zero-fee index funds and great education resources", cost: "Free to open", free: true },
        { name: "Vanguard", domain: "vanguard.com", url: "https://vanguard.com", note: "Pioneer of low-cost index investing — ideal for long-term, set-it-and-forget-it portfolios", cost: "Free to open", free: true },
        { name: "Charles Schwab", domain: "schwab.com", url: "https://schwab.com", note: "No minimums, fractional shares, and excellent beginner tools alongside full brokerage services", cost: "Free to open", free: true },
        { name: "M1 Finance", domain: "m1.com", url: "https://m1.com", note: "Automate your portfolio with pie-based investing — set your allocation once and contributions invest themselves", cost: "Free (M1 Plus: $3/mo)", free: true },
        { name: "Acorns", domain: "acorns.com", url: "https://acorns.com", note: "Rounds up spare change from purchases and invests automatically — best for building the habit from zero", cost: "$3–$5/mo", free: false },
      ],
    },
    credit: {
      title: "Credit 101",
      eyebrow: "Education",
      summary: "Understand utilization, payment history, credit mix, hard inquiries, and how to protect your score early.",
      audience: "Anyone opening a first card, using student loans, or preparing for apartments, cars, or future borrowing.",
      outcomes: ["Calculate utilization", "Explain why payment history matters", "Build safer credit habits"],
      sections: [
        {
          title: "Credit is a reputation system",
          body: "A credit score summarizes how lenders view your borrowing behavior. Payment history and utilization are especially important because they show whether you pay on time and how much available credit you use.",
        },
        {
          title: "Utilization is controllable",
          body: "Credit utilization compares your balance with your credit limit. Learning how it works helps you avoid accidentally looking overextended, even when you pay the bill later.",
        },
        {
          title: "AI can help you plan, not borrow",
          body: "Use AI to create bill reminders, compare payoff scenarios, and explain credit terms. Do not use AI outputs as permission to take on debt you do not understand.",
        },
      ],
      checklist: ["Pay on time", "Track statement dates", "Keep utilization visible", "Avoid applying for credit randomly", "Read terms before signing"],
      prompt: "Help me understand this credit decision. Explain the terms, possible risks, payment timeline, and questions I should ask before borrowing. Do not tell me to apply.",
    },
    budgeting: {
      title: "Budgeting",
      eyebrow: "Education",
      summary: "Build a simple system for income, expenses, savings, debt, and flexibility.",
      audience: "Students with part-time income, interns, new grads, and anyone trying to create a weekly money routine.",
      outcomes: ["Separate fixed and flexible costs", "Create a weekly review habit", "Find spending patterns faster"],
      sections: [
        {
          title: "A budget is a control panel",
          body: "A budget is not punishment. It is a visibility system. It shows where money is going and helps you make tradeoffs before your account balance surprises you.",
        },
        {
          title: "Make it weekly",
          body: "Monthly budgets are useful, but weekly reviews are easier for students. Check income, upcoming bills, food, subscriptions, social spending, and savings before the week starts.",
        },
        {
          title: "Use AI to classify and reflect",
          body: "AI can group transactions, summarize patterns, and turn messy spending into a short action list. Always remove private data before pasting anything into a tool.",
        },
      ],
      checklist: ["List fixed costs", "Estimate flexible spending", "Choose a savings target", "Review weekly", "Adjust without guilt"],
      prompt: "Review this anonymized budget. Categorize expenses, identify patterns, suggest three realistic changes, and create a one-week action plan.",
    },
    ai: {
      title: "AI for Personal Finance",
      eyebrow: "Education",
      summary: "Use AI to organize questions, compare options, summarize financial topics, and build better habits.",
      audience: "Beginners who want AI help without outsourcing judgment.",
      outcomes: ["Write better prompts", "Verify AI outputs", "Use AI for planning and automation safely"],
      sections: [
        {
          title: "AI is a thinking partner",
          body: "AI is best used to clarify, summarize, organize, draft, and generate questions. It should not replace professional advice or make final decisions for you.",
        },
        {
          title: "Protect your data",
          body: "Do not paste full account numbers, passwords, tax IDs, or private financial documents into public tools. Use anonymized examples whenever possible.",
        },
        {
          title: "Use AI with verification",
          body: "Ask AI for sources, assumptions, and alternative explanations. Then verify important information with official documents or trusted sources.",
        },
      ],
      checklist: ["Remove private data", "Ask for assumptions", "Request sources", "Compare multiple options", "Make the final decision yourself"],
      prompt: "Act as a financial education assistant. Ask me clarifying questions, explain tradeoffs, list assumptions, and help me create a safe next-step checklist.",
    },
    careers: {
      title: "Finance Careers",
      eyebrow: "Education",
      summary: "Connect classroom finance to internships, networking, resumes, and interview preparation.",
      audience: "Students trying to turn finance interest into opportunity.",
      outcomes: ["Map career paths", "Improve networking messages", "Prepare stronger interview stories"],
      sections: [
        {
          title: "Careers are built through signals",
          body: "Employers look for curiosity, preparation, communication, and evidence you can learn. Projects, internships, clubs, and outreach all create signals.",
        },
        {
          title: "Use AI to prepare faster",
          body: "AI can research companies, draft outreach, practice interview questions, and improve resume bullets. Personalize everything before sending.",
        },
        {
          title: "Build a simple pipeline",
          body: "Track target roles, contacts, application dates, follow-ups, and interview notes. A lightweight system beats random last-minute applying.",
        },
      ],
      checklist: ["Pick target roles", "Research 10 firms", "Draft outreach", "Improve resume bullets", "Practice behavioral stories"],
      prompt: "Help me prepare for a finance internship search. Create a target company research checklist, outreach draft, resume improvement ideas, and interview practice questions.",
    },
    entrepreneurship: {
      title: "Entrepreneurship",
      eyebrow: "Education",
      summary: "Explore cash flow, pricing, margins, customer discovery, and small business fundamentals.",
      audience: "Students building side projects, services, creator businesses, or early startup ideas.",
      outcomes: ["Understand cash flow", "Think through pricing", "Use AI to prototype and automate"],
      sections: [
        {
          title: "A business is a money system",
          body: "Revenue, costs, margins, cash timing, and customer demand matter. A great idea still needs a model that can survive reality.",
        },
        {
          title: "AI makes small teams stronger",
          body: "AI can help draft landing pages, write outreach, analyze customer feedback, create simple code, and automate repetitive admin tasks.",
        },
        {
          title: "Validate before scaling",
          body: "Talk to customers, test pricing, measure demand, and avoid building too much before learning what people actually want.",
        },
      ],
      checklist: ["Define the customer", "List costs", "Estimate margins", "Test one offer", "Automate one repetitive task"],
      prompt: "Act as a startup coach. Help me test this business idea by identifying customers, pricing assumptions, costs, risks, and a simple AI automation I can build.",
    },
    diversification: {
      title: "Diversification & Asset Allocation",
      eyebrow: "Education",
      summary: "Learn why spreading risk across different assets is one of the most powerful tools in investing.",
      audience: "Anyone building or starting an investment portfolio who wants to reduce risk without sacrificing long-term returns.",
      outcomes: ["Understand why diversification reduces risk", "Learn the main asset classes", "Build a simple allocation starting point"],
      sections: [
        {
          title: "Don't put everything in one basket",
          body: "Diversification means owning different types of investments so a loss in one area does not wipe out everything. When stocks fall, bonds may hold. When one sector struggles, another may thrive. The goal is resilience, not perfection.",
        },
        {
          title: "Asset classes that behave differently",
          body: "Stocks, bonds, real estate investment trusts, and cash all respond differently to economic conditions. Mixing them creates a portfolio more capable of surviving market events without you having to react emotionally.",
        },
        {
          title: "Index funds make diversification automatic",
          body: "A single S&P 500 index fund gives you exposure to 500 companies across every major sector. That is instant diversification at a very low cost — no stock picking required.",
        },
      ],
      checklist: ["List your current holdings by category", "Count how many sectors you are in", "Identify any heavy concentrations", "Consider low-cost index ETFs for base exposure", "Review allocation at least once a year"],
      prompt: "Act as a portfolio coach. Analyze this set of holdings for concentration risk, suggest a more diversified allocation, and explain the tradeoffs of each change. Use plain educational language only — no buy or sell recommendations.",
    },
    stocks: {
      title: "Types of Stocks",
      eyebrow: "Education",
      summary: "Understand the difference between growth, value, and dividend stocks, and how market cap shapes your risk.",
      audience: "Beginners building their first watchlist who want to categorize stocks before forming opinions.",
      outcomes: ["Tell growth stocks from value and dividend stocks", "Understand large, mid, and small cap categories", "Build a basic stock evaluation checklist"],
      sections: [
        {
          title: "Growth, value, and dividend — three different bets",
          body: "Growth stocks reinvest earnings to expand fast — higher upside, higher risk. Value stocks trade below estimated fair value and tend to be more stable businesses. Dividend stocks pay regular income, making them popular for long-term holders who want cash flow.",
        },
        {
          title: "Market cap tells you the company's size and risk level",
          body: "Large-cap companies are established giants like Apple or JPMorgan — lower risk, slower growth. Mid-cap companies are growing businesses with more upside. Small-cap companies are earlier stage with the most risk and most potential reward.",
        },
        {
          title: "Use AI to research, not to decide",
          body: "Ask AI to explain a company's business model, revenue drivers, and key risks. Then verify with the company's own filings and trusted financial sources. AI is a research accelerator, not a stock picker.",
        },
      ],
      checklist: ["Define your goal: income, growth, or stability", "Research the company's business model in plain terms", "Identify its market cap category", "Look at performance across different market conditions", "Compare it to at least two alternatives"],
      prompt: "Help me understand this stock. Explain its business model, revenue sources, competitive risks, and how it compares to similar companies. Use plain language and do not make a buy or sell recommendation.",
    },
    etfs: {
      title: "ETFs & Index Investing",
      eyebrow: "Education",
      summary: "Learn how exchange-traded funds work and why low-cost passive investing beats most active strategies over time.",
      audience: "Beginners who want broad market exposure without picking individual stocks or paying high fees.",
      outcomes: ["Explain what an ETF is and how it trades", "Compare ETFs to mutual funds", "Understand expense ratios and why they compound against you"],
      sections: [
        {
          title: "An ETF is a basket of investments in one share",
          body: "When you buy one share of an ETF, you get exposure to every security inside it. A total market ETF might hold thousands of stocks. You get diversification immediately, without needing to buy each company separately.",
        },
        {
          title: "Index funds track the market instead of trying to beat it",
          body: "Rather than guessing which stocks will outperform, index funds match the market. Research consistently shows that most active fund managers underperform simple index strategies over 10 to 20 years — especially after fees.",
        },
        {
          title: "Expense ratios are a hidden drag on returns",
          body: "A 1% annual fee versus a 0.03% fee sounds small. Over 30 years on a $50,000 portfolio, it can cost more than $100,000 in lost growth. Always compare expense ratios before choosing between similar funds.",
        },
      ],
      checklist: ["Look up the expense ratio before buying any fund", "Identify what index or benchmark the fund tracks", "Check how liquid the ETF is (daily volume)", "Compare at least two similar ETFs", "Understand what sectors and regions you are buying exposure to"],
      prompt: "Help me understand this ETF or index fund. Explain what it holds, its expense ratio, what index it tracks, and how it compares to similar options. Give me an educational summary without making a recommendation.",
    },
    // ── New chapters ────────────────────────────────────────────────────────
    reset: {
      title: "Money Reset",
      eyebrow: "Chapter 1",
      summary: "Understand exactly where you stand financially before making any other move.",
      audience: "Anyone who feels uncertain, behind, or just wants an honest picture of their finances.",
      outcomes: ["Calculate your real net worth", "Map income vs. expenses clearly", "Complete a 3-step money reset checklist"],
      sections: [
        {
          title: "Start with what you actually have",
          body: "A money reset begins with honesty, not judgment. Net worth is simply what you own minus what you owe. It can be negative when you're starting out — that's completely normal. Knowing the number is what matters, not what the number is right now.",
        },
        {
          title: "Income vs. expenses: the most important equation",
          body: "List every source of income and every regular expense. Most people discover they're spending more than they realized in at least one category. This is valuable information, not bad news. Seeing it clearly is the first step.",
        },
        {
          title: "The 3-step money reset checklist",
          body: "Step 1: List every account — checking, savings, credit cards, loans, investments. Step 2: Calculate net worth (total assets minus total liabilities). Step 3: Identify the one spending category that surprises you most. That's where to focus first — everything else follows.",
        },
      ],
      checklist: ["List all accounts and current balances", "Add up assets and liabilities", "Calculate your net worth (even if negative)", "Track all income for one full month", "Find your single biggest surprise expense"],
      prompt: "Act as a financial coach. Help me do a simple money reset. Ask me about my monthly income, fixed expenses, variable spending, savings, and debts. Then summarize my financial picture in plain language and give me three specific things to focus on first. Do not make investment or legal recommendations — help me see clearly.",
    },
    debt_payoff: {
      title: "Debt Payoff Strategy",
      eyebrow: "Chapter 4",
      summary: "Compare snowball vs. avalanche and build a realistic plan to pay down debt faster.",
      audience: "Anyone with multiple debts who wants a clear strategy instead of just making minimum payments.",
      outcomes: ["Understand how interest compounds on debt", "Compare snowball vs. avalanche methods", "Build a prioritized payoff order"],
      sections: [
        {
          title: "Minimum payments keep you stuck",
          body: "Paying only the minimum on a credit card can take years to clear a small balance, because interest compounds on the remaining amount each month. Understanding this is the first step to getting free.",
        },
        {
          title: "Snowball: smallest balance first",
          body: "The snowball method pays off debts from smallest balance to largest, ignoring interest rates. Each paid-off debt creates momentum and motivation. Research shows this method helps people who need visible wins to stay on track.",
        },
        {
          title: "Avalanche: highest interest rate first",
          body: "The avalanche method attacks the highest-interest debt first. Mathematically, this saves the most money over time. It works best for people who are motivated by numbers and long-term savings over quick psychological wins.",
        },
      ],
      checklist: ["List every debt with balance, rate, and minimum payment", "Add up total debt", "Choose snowball or avalanche based on your motivation style", "Find at least one extra dollar per month to apply to your target debt", "Track your payoff progress monthly"],
      prompt: "Act as a debt payoff coach. Here are my debts: [LIST — include name, current balance, interest rate %, and minimum monthly payment for each]. Show me the payoff order using both the snowball method and avalanche method. Estimate how long each takes and which saves more total interest. Use plain numbers and realistic language.",
    },
  },
  workflows: {
    budgeting: {
      title: "AI Budgeting Workflow",
      summary: "Use AI to turn messy spending data into categories, patterns, and weekly actions.",
      steps: ["Export or write out your spending in anonymized categories (no account numbers)", "Paste into ChatGPT or Claude and ask it to group expenses by type", "Identify your top three spending leaks", "Build a realistic weekly spending plan based on those patterns", "Set up a spreadsheet or app to automate weekly tracking"],
      automation: "Use a Google Sheet with AI-generated formulas to flag subscriptions, high-frequency purchases, and weekly budget drift automatically.",
      prompt: "Here is anonymized spending by merchant and amount. Categorize it, find patterns, flag recurring charges, and create a realistic one-week action plan.",
      resources: [
        { name: "ChatGPT", url: "https://chat.openai.com", note: "Run the categorization and analysis prompt here" },
        { name: "Claude", url: "https://claude.ai", note: "Alternative AI — great for structured summaries" },
        { name: "YNAB", url: "https://ynab.com", note: "Best app for zero-based budgeting and tracking" },
        { name: "Copilot Money", url: "https://copilot.money", note: "AI-powered budgeting app that auto-categorizes" },
        { name: "Google Sheets", url: "https://sheets.google.com", note: "Free — build your own tracker with AI-generated formulas" },
      ],
    },
    networking: {
      title: "AI Internship Networking Workflow",
      summary: "Use AI to research firms, personalize outreach, and follow up without sounding generic.",
      steps: ["List your target companies and the role type you are pursuing", "Ask AI to generate 5 research questions specific to each firm", "Draft a short (4–5 sentence) outreach message using AI", "Personalize every message with a real detail from your research", "Track every contact, follow-up date, and response in a spreadsheet"],
      automation: "Use AI to generate a tracking spreadsheet structure with columns for contact, company, role, date, status, and next action — then keep it updated weekly.",
      prompt: "Help me research this company for an internship. Summarize what they do, recent developments, possible entry-level roles, and write a concise outreach draft I can personalize.",
      resources: [
        { name: "ChatGPT", url: "https://chat.openai.com", note: "Draft outreach and research questions" },
        { name: "LinkedIn", url: "https://linkedin.com", note: "Research firms, employees, and alumni connections" },
        { name: "Glassdoor", url: "https://glassdoor.com", note: "Read interview experiences and company reviews" },
        { name: "Hunter.io", url: "https://hunter.io", note: "Find professional email addresses" },
        { name: "Notion", url: "https://notion.so", note: "Free — build a clean application tracker" },
      ],
    },
    resume: {
      title: "AI Resume Improvement Workflow",
      summary: "Use AI to turn vague experience into sharper, measurable bullets.",
      steps: ["Pick one resume bullet that feels weak or vague", "Paste it into AI and ask it to identify the skill and the missing result", "Ask for three rewritten versions with action verbs and measurable impact", "Fact-check every rewrite — never let AI invent numbers", "Tailor the best version to the specific role description"],
      automation: "Build a reusable prompt library in Notion so every resume edit follows the same structure and stays honest and consistent.",
      prompt: "Rewrite this resume bullet for a finance internship. Make it clearer, action-oriented, and measurable without inventing facts. Give me three versions.",
      resources: [
        { name: "ChatGPT", url: "https://chat.openai.com", note: "Generate and improve resume bullets" },
        { name: "Claude", url: "https://claude.ai", note: "Good for longer edits and structured rewrites" },
        { name: "Grammarly", url: "https://grammarly.com", note: "Catch grammar issues before submitting" },
        { name: "LinkedIn Jobs", url: "https://linkedin.com/jobs", note: "Pull keywords from job postings to tailor bullets" },
        { name: "Google Docs", url: "https://docs.google.com", note: "Free — write, format, and share your resume" },
      ],
    },
    investing: {
      title: "AI Investing Research Workflow",
      summary: "Use AI to summarize sources, compare risks, and generate questions before forming an opinion.",
      steps: ["Choose one company or fund to study — start with something you already know", "Find official sources: the company's investor relations page and SEC filings", "Ask AI to summarize the business model, revenue drivers, and listed risks", "Generate a list of questions you cannot yet answer", "Verify every AI output against the original source before forming a view"],
      automation: "Use AI to create a research checklist and a spreadsheet template for sources, assumptions, risks, and open questions — rebuild it for every new investment you study.",
      prompt: "Summarize this investment source for education. Identify business model, risks, key terms, assumptions, and questions I should research further. Do not recommend buying or selling.",
      resources: [
        { name: "ChatGPT", url: "https://chat.openai.com", note: "Summarize filings and generate research questions" },
        { name: "SEC EDGAR", url: "https://sec.gov/cgi-bin/browse-edgar", note: "Official U.S. company filings — always verify here" },
        { name: "Yahoo Finance", url: "https://finance.yahoo.com", note: "Free — financials, news, and analyst estimates" },
        { name: "Morningstar", url: "https://morningstar.com", note: "Fund analysis and long-term performance data" },
        { name: "Investopedia", url: "https://investopedia.com", note: "Define any term you do not understand" },
      ],
    },
    productivity: {
      title: "AI Productivity Workflow",
      summary: "Use AI to turn goals into weekly priorities, study plans, and repeatable systems.",
      steps: ["Write out every goal and deadline you are working toward right now", "Ask AI to rank them by urgency and impact", "Build a weekly plan with specific time blocks for each priority", "Set one recurring review slot per week to check your progress", "Automate reminders so the system runs without you having to remember it"],
      automation: "Use AI to draft calendar blocks, checklist templates, and recurring review prompts for school, money, and career tasks — then copy them into your tool of choice.",
      prompt: "Turn these goals into a weekly plan with priorities, time blocks, reminders, and a simple review checklist.",
      resources: [
        { name: "ChatGPT", url: "https://chat.openai.com", note: "Build plans, rank priorities, write checklists" },
        { name: "Notion", url: "https://notion.so", note: "Free — organize goals, notes, and weekly reviews" },
        { name: "Google Calendar", url: "https://calendar.google.com", note: "Block time for priorities and recurring reviews" },
        { name: "Todoist", url: "https://todoist.com", note: "Simple task manager with priority levels" },
        { name: "Reclaim.ai", url: "https://reclaim.ai", note: "AI that auto-schedules tasks around your calendar" },
      ],
    },
    coding: {
      title: "AI Coding + Automation Workflow",
      summary: "Use AI coding tools to build small automations that save time and improve your financial habits.",
      steps: ["Pick one repetitive task you do weekly — tracking subscriptions, splitting income, logging applications", "Describe the exact input and desired output to AI in plain English", "Ask AI to draft a beginner-friendly script or Google Sheets formula", "Test with fake data before connecting anything real", "Schedule or reuse the automation so it runs without manual effort"],
      automation: "Start small: subscription tracker, budget category cleaner, paycheck splitter, or job application logger. Each one teaches you a reusable pattern.",
      prompt: "Help me build a simple automation for this task. Ask clarifying questions, define inputs and outputs, write beginner-friendly code or spreadsheet formulas, and include test cases with fake data.",
      resources: [
        { name: "ChatGPT", url: "https://chat.openai.com", note: "Generate scripts, formulas, and step-by-step code" },
        { name: "Google Sheets", url: "https://sheets.google.com", note: "Free — build automations with AI-generated formulas" },
        { name: "Python (Beginner)", url: "https://python.org/about/gettingstarted", note: "Free language for simple financial scripts" },
        { name: "Zapier", url: "https://zapier.com", note: "No-code automations connecting your favorite apps" },
        { name: "Replit", url: "https://replit.com", note: "Run Python in your browser — no install needed" },
      ],
    },

    // ── AI Money Playbooks ───────────────────────────────────────────────────
    budget_quick: {
      title: "Build a Weekly Budget in 10 Minutes",
      summary: "A fast, simple workflow for anyone who has avoided budgeting because it felt too complicated or overwhelming.",
      steps: [
        "Write down your monthly take-home income (after taxes and deductions)",
        "List your fixed monthly expenses: rent, subscriptions, loan payments, insurance",
        "Estimate flexible spending: food, transport, entertainment, personal care",
        "Subtract fixed + flexible from income — what remains is your slack",
        "Split your slack into: savings target + small buffer + discretionary allowance",
        "Set a 5-minute Sunday review: open your bank app and compare plan vs. reality",
      ],
      automation: "Create a simple Google Sheet with your categories as rows. Set a recurring Sunday calendar reminder titled '5-min budget check.' AI can generate the formulas and row structure for you.",
      prompt: "I want to build a simple weekly budget. My monthly take-home income is [AMOUNT]. My fixed monthly expenses include [LIST]. My flexible spending usually goes toward [CATEGORIES]. Create a realistic weekly budget that splits income into needs, wants, savings, and a small buffer. Keep it simple enough to actually maintain.",
      resources: [
        { name: "ChatGPT", url: "https://chat.openai.com", note: "Run the prompt above to build your budget draft" },
        { name: "YNAB", url: "https://ynab.com", note: "Best for zero-based budgeting — free trial available" },
        { name: "Copilot Money", url: "https://copilot.money", note: "AI-powered budget app that auto-categorizes spending" },
        { name: "Google Sheets", url: "https://sheets.google.com", note: "Free — copy a template and customize with AI help" },
        { name: "Notion", url: "https://notion.so", note: "Simple budget tracker with free templates" },
      ],
    },
    categorize: {
      title: "Turn Messy Spending into Categories",
      summary: "Use AI to clean up confusing transaction data and see exactly where your money is going each month.",
      steps: [
        "Export one month of transactions from your bank (CSV download or screenshot)",
        "Remove all account numbers, full names, and any sensitive information before pasting",
        "Paste only the anonymized merchant names and amounts into the AI prompt below",
        "Ask AI to group them into categories: Food, Transport, Subscriptions, Entertainment, etc.",
        "Review the categories — correct any that AI got wrong",
        "Identify your top 3 spending categories and your single biggest surprise",
      ],
      automation: "Download your bank CSV monthly, use a Google Sheet to auto-sort by merchant, and run AI analysis each month to track category trends over time.",
      prompt: "Here are my anonymized transactions for the month: [PASTE MERCHANT NAME + AMOUNT, one per line, no personal info]. Group these into spending categories, calculate the total per category, identify my top 3 categories, and flag any recurring charges. Give me a 4-sentence summary and one realistic suggestion.",
      resources: [
        { name: "ChatGPT", url: "https://chat.openai.com", note: "Paste anonymized transactions and run the prompt" },
        { name: "Claude", url: "https://claude.ai", note: "Good for longer lists and structured category outputs" },
        { name: "Monarch Money", url: "https://monarchmoney.com", note: "Automatic transaction categorization — free trial" },
        { name: "Google Sheets", url: "https://sheets.google.com", note: "Manual categorization with AI-generated formulas" },
        { name: "NerdWallet", url: "https://nerdwallet.com", note: "Compare budgeting apps before you commit to one" },
      ],
    },
    debt_plan: {
      title: "Create a Debt Payoff Plan",
      summary: "Organize your debts, compare strategies, and build a realistic month-by-month timeline to get debt-free.",
      steps: [
        "List every debt: credit cards, student loans, personal loans, car payments",
        "For each debt, record: current balance, interest rate (APR), and minimum monthly payment",
        "Choose your method: snowball (smallest balance first) or avalanche (highest rate first)",
        "Calculate how much extra you can put toward debt each month beyond minimums",
        "Apply all extra money to your one target debt while paying minimums on everything else",
        "After each payoff, roll that payment amount into the next target — this is the debt snowball effect",
      ],
      automation: "Ask AI to generate a Google Sheet template with your debts as rows, payoff date formulas, and a running total of interest saved vs. minimum-only payments.",
      prompt: "Help me create a debt payoff plan. Here are my debts: [LIST EACH: Name, Balance, Interest Rate %, Minimum Monthly Payment]. Show me the payoff order and estimated timeline using both the snowball method and the avalanche method. Which saves more money in total interest? Use plain numbers.",
      resources: [
        { name: "ChatGPT", url: "https://chat.openai.com", note: "Generate your payoff plan and comparison" },
        { name: "Undebt.it", url: "https://undebt.it", note: "Free debt payoff calculator — snowball and avalanche" },
        { name: "CFPB Debt Tools", url: "https://consumerfinance.gov/consumer-tools/credit-cards/", note: "Free government resources on credit card payoff" },
        { name: "NerdWallet Payoff Calc", url: "https://nerdwallet.com/article/finance/debt-payoff-calculator", note: "Side-by-side method comparison" },
        { name: "Google Sheets", url: "https://sheets.google.com", note: "Build a custom tracker with AI-generated formulas" },
      ],
    },
    invest_path: {
      title: "Build a Beginner Investing Learning Path",
      summary: "Go from zero knowledge to confident beginner with a structured 8-week education plan built around index investing.",
      steps: [
        "Assess your starting point: have you opened a brokerage or retirement account yet?",
        "Learn core vocabulary first: stocks, bonds, ETFs, index funds, expense ratio, dividends",
        "Understand risk tolerance: how long can this money stay invested without you needing it?",
        "Study index funds: what is the S&P 500, what is a total market fund, and what does 'low-cost' mean?",
        "Open a paper trading account to practice with zero real risk",
        "Set a learning goal: one new investing concept per week for 8 weeks, tracked in Notion",
      ],
      automation: "Use Notion to track your 8-week plan. Ask AI to create a weekly schedule with one concept, one question to answer, and one action step for each week.",
      prompt: "I am a beginner investor. My knowledge level is [BEGINNER / KNOW SOME BASICS / SOME EXPERIENCE]. I can invest approximately $[AMOUNT] per month and my time horizon is [SHORT / MEDIUM / LONG TERM]. Create a personalized 8-week investing education plan. Each week should include: one concept to study, one question to answer, and one low-risk action to take. Focus on index funds and long-term strategy. Add an educational disclaimer at the end.",
      resources: [
        { name: "ChatGPT", url: "https://chat.openai.com", note: "Generate your personalized 8-week plan" },
        { name: "Investopedia", url: "https://investopedia.com", note: "Best free investing dictionary and topic explainers" },
        { name: "Fidelity Learning Center", url: "https://fidelity.com/learning-center/overview", note: "Free beginner courses from a major brokerage" },
        { name: "Bogleheads Wiki", url: "https://bogleheads.org/wiki/Main_Page", note: "Community-built guide to index investing" },
        { name: "SEC Investor Education", url: "https://investor.gov", note: "Official U.S. government investor resources" },
      ],
    },
    network_email: {
      title: "Write a Networking Email for Finance Internships",
      summary: "Research a target firm, draft a concise professional outreach message, and follow up the right way.",
      steps: [
        "Identify one target company and find a relevant contact: analyst, associate, or recruiter on LinkedIn",
        "Research the company: recent news, culture, entry-level hiring, and what the team does",
        "Draft a short email: a subject line, a 3-sentence body, and one clear low-pressure ask",
        "Personalize with one specific detail from your research — make it obvious you did homework",
        "Send from a professional email address (not a nickname or old username)",
        "Follow up once after 5–7 business days with a single sentence if no response",
      ],
      automation: "Keep a spreadsheet with columns: Name, Company, Role, Date Sent, Follow-Up Date, Response. Review it every Monday morning.",
      prompt: "Help me write a cold networking email for a finance internship. My name is [YOUR NAME]. I am a [YEAR/MAJOR] student at [SCHOOL]. I am reaching out to [THEIR NAME], who is a [THEIR ROLE] at [COMPANY]. I am interested in [TEAM OR ROLE]. One real thing I know about this company is [FACT]. Write a subject line and a 3-sentence email body with a clear, low-pressure ask. Give me two versions: one formal, one slightly warmer.",
      resources: [
        { name: "ChatGPT", url: "https://chat.openai.com", note: "Draft and refine your outreach email" },
        { name: "LinkedIn", url: "https://linkedin.com", note: "Find the right contact and research the company" },
        { name: "Glassdoor", url: "https://glassdoor.com", note: "Read culture and hiring insights from employees" },
        { name: "Hunter.io", url: "https://hunter.io", note: "Find professional email addresses by company domain" },
        { name: "Notion", url: "https://notion.so", note: "Free — track outreach, contacts, and follow-ups" },
      ],
    },
    compare_tools: {
      title: "Compare Financial Tools Before Choosing One",
      summary: "Use AI to evaluate apps, accounts, and financial products side by side before committing to any of them.",
      steps: [
        "Define what problem you are trying to solve: saving, budgeting, investing, or building credit",
        "List 2–4 tools or products you are considering",
        "Ask AI to compare features, costs, pros, and cons for each",
        "Cross-check AI output against the product's actual website — verify fees and features",
        "Read real user reviews on Reddit r/personalfinance and the App Store",
        "Choose based on your actual habits and lifestyle, not just the best feature list",
      ],
      automation: "Build a simple comparison table in Notion or Google Sheets: tool name, monthly cost, main feature, biggest downside, review rating, and your personal priority score.",
      prompt: "Compare these financial tools for me: [LIST TOOL NAMES]. I am trying to [GOAL: budget / save / invest / build credit]. For each tool, tell me: what it does, who it is best for, the monthly cost (if any), the main downside, and where I can read trustworthy reviews. Do not tell me which to choose — give me the information to decide. Keep each comparison to 4–5 sentences.",
      resources: [
        { name: "ChatGPT", url: "https://chat.openai.com", note: "Get structured side-by-side comparisons" },
        { name: "NerdWallet Reviews", url: "https://nerdwallet.com", note: "Independent reviews of financial apps and accounts" },
        { name: "Investopedia Reviews", url: "https://investopedia.com/reviews", note: "Detailed product comparisons and ratings" },
        { name: "Reddit r/personalfinance", url: "https://reddit.com/r/personalfinance", note: "Real community opinions on apps and products" },
        { name: "CFPB Consumer Tools", url: "https://consumerfinance.gov", note: "Official U.S. financial product information and complaints" },
      ],
    },
  },
  tools: {
    compound: {
      title: "Compound Interest Calculator",
      summary: "Model how monthly contributions, time, and assumed return can affect long-term growth.",
      inputs: ["Monthly contribution", "Years invested", "Annual return assumption"],
      useCases: ["Compare starting now versus later", "Understand contribution impact", "Visualize compounding"],
    },
    credit: {
      title: "Credit Utilization Calculator",
      summary: "Estimate utilization and see how balance changes can affect your ratio.",
      inputs: ["Current balance", "Credit limit", "Target utilization"],
      useCases: ["Plan card payments", "Understand utilization", "Avoid accidental overuse"],
    },
    budget: {
      title: "Budget Builder",
      summary: "Create an editable monthly budget split and see category totals in a live chart.",
      inputs: ["Income", "Needs", "Wants", "Savings/debt"],
      useCases: ["Build a first budget", "Rebalance spending", "Plan weekly habits"],
    },
    salary: {
      title: "Salary Breakdown Calculator",
      summary: "Translate salary into monthly, weekly, and hourly planning numbers.",
      inputs: ["Annual salary", "Deduction rate", "Hours per week"],
      useCases: ["Compare offers", "Plan rent limits", "Estimate take-home"],
    },
    afford: {
      title: "Can I Afford This? Analyzer",
      summary: "Compare purchase cost with income, savings target, and opportunity cost.",
      inputs: ["Purchase cost", "Monthly income", "Savings goal"],
      useCases: ["Pause before buying", "Compare tradeoffs", "Protect goals"],
    },
    finder: {
      title: "AI Finance Tool Finder",
      summary: "Choose a money or career task and get a responsible AI workflow.",
      inputs: ["Goal", "Current skill level", "Desired output"],
      useCases: ["Pick a workflow", "Learn better prompts", "Avoid misusing AI"],
    },

    // ── New tools ────────────────────────────────────────────────────────────
    emergency: {
      title: "Emergency Fund Calculator",
      summary: "Enter your monthly essential expenses and see your 1-, 3-, and 6-month emergency fund targets.",
      inputs: ["Monthly essential expenses (rent, food, transport, utilities)"],
      useCases: ["Set a realistic savings target", "Understand how much cushion is enough", "Build confidence around your safety net"],
    },
    debt_planner: {
      title: "Debt Payoff Planner",
      summary: "Enter your debts and see a snowball vs. avalanche comparison with estimated payoff timelines.",
      inputs: ["Debt balance", "Interest rate (APR)", "Minimum monthly payment"],
      useCases: ["Compare payoff strategies side by side", "Estimate total interest saved", "Build your payoff order"],
    },
    email_gen: {
      title: "Networking Email Generator",
      summary: "Fill in a few fields and get a clean, professional networking email template you can personalize.",
      inputs: ["Your name and school", "Their name and role", "Company name", "Your goal"],
      useCases: ["Cold outreach to analysts and recruiters", "Informational interview requests", "Follow-up after events or applications"],
    },
    invest_guide: {
      title: "Investing Learning Path",
      summary: "Choose your experience level and get a personalized beginner roadmap to index investing.",
      inputs: ["Experience level", "Time horizon", "Monthly amount you can invest"],
      useCases: ["Learn in the right order", "Avoid common first-timer mistakes", "Build confidence before risking real money"],
    },
  },
};
